import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { useSession, signOut, signIn } from 'next-auth/client'

export default function Home() {
  const [session, loading] = useSession()

  if (session) {
    console.log(session)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>Welcome to Save for Later!</h1>

      <main className={styles.main}>
        {session ? (
          <>
            <h3>Signed in as {session.user?.name}</h3>
            <button onClick={() => signOut()}>Sign Out</button>
            <a href='/brain'>Visit your brain</a>
          </>
        ) : (
          <>
            <h3>Not signed in</h3>
            {/* <a href='/api/auth/signin'>Sign In</a> */}
            <button onClick={() => signIn('github')}>Sign In</button>
          </>
        )}
      </main>
    </div>
  )
}
